server:
  port: 8888
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./acnovate
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true